In [2]:
import pandas as pd 
import sqlite3

In [3]:
import sqlite3
import pandas 
conn = sqlite3.connect(r"C:/Users/Hp/Downloads/database (4).sqlite")
cursor = conn.cursor()

print("Database connected!")

Database connected!

In [4]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('Salaries',)]

In [10]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM Salaries;", conn)
df.head()   # pehle 5 rows dekhne ke liye

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [5]:
query = """
SELECT 
    JobTitle,
    AVG(TotalPayBenefits) AS avg_TotalPayBenefits
FROM 
    Salaries
WHERE 
    JobTitle NOT IN ('Not Provided', 'Not provided')
GROUP BY 
    JobTitle;
"""

df_avg = pd.read_sql_query(query, conn)
df_avg

                                            JobTitle  avg_TotalPayBenefits
0                                      ACCOUNT CLERK          44035.664337
1                                         ACCOUNTANT          47429.268000
2                                  ACCOUNTANT INTERN          29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)          80266.370000
4                                      ACUPUNCTURIST          67594.400000
...                                              ...                   ...
2153                           X-RAY LABORATORY AIDE          52705.880385
2154                           X-Ray Laboratory Aide          69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS          53632.870000
2156                              Youth Comm Advisor          60118.550000
2157                                     ZOO CURATOR          66686.560000

[2158 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [8]:
pd.read_sql_query(
    '''
    SELECT DISTINCT EmployeeName 
    FROM Salaries 
    WHERE EmployeeName NOT IN ("Not Provided", "Not provided")
    ''',
    conn
)

              EmployeeName
0           NATHANIEL FORD
1           ALBERT PARDINI
2        CHRISTOPHER CHONG
3          PATRICK GARDNER
4           DAVID SULLIVAN
...                    ...
110803   Afakasi O Afakasi
110804      Kenneth Mackey
110805      Mark W Mcclure
110806  Charlene D Mccully
110807           Joe Lopez

[110808 rows x 1 columns]

#### **4.Show The Top 10 highest Paid Employees**

In [9]:
pd.read_sql_query(
    '''
    SELECT 
        EmployeeName,
        JobTitle,
        TotalPayBenefits
    FROM Salaries
    ORDER BY TotalPayBenefits DESC
    LIMIT 10;
    ''',
    conn
)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [10]:
pd.read_sql_query(
    '''
    SELECT 
        EmployeeName,
        JobTitle,
        TotalPayBenefits
    FROM Salaries
    ORDER BY TotalPayBenefits DESC;
    ''',
    conn
)

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148648,Not provided,Not provided,0.00
148649,Timothy E Gibson,Police Officer 3,-2.73
148650,Mark E Laherty,Police Officer 3,-8.20
148651,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13